### ISSUE TITLE
'Sort ▲' and 'Sort ▼' remain untranslatable in 2.1.3-5

### ISSUE THREAD

**Issue by dikonov** [accumulator/kodimote#4]
In 2.1.3-5 the 'Search' got translated through the updated .ts but 'Sort ▲' and 'Sort ▼' remained English. The kodimote_ru.ts file does have the translations for them.

BTW. Where do the translations go in the compiled version? I could not find the regular .qm files.

**Comment by accumulator** [comment]
They are linked in the binary. Here is more information: https://doc.qt.io/qt-5/resources.html
